debug: false
management.endpoint.web.exposure.include: "*"

logging:
  level:
    com.fastcampus.webpage_prac: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace #????? ???? ?? ??

spring:
  datasource:
    url: jdbc:mysql://ec2-13-209-64-91.ap-northeast-2.compute.amazonaws.com:3306/board
    username: guest
    password: guest
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true     #???? ?? ??? ??
    hibernate.ddl-auto: create                #???? ?? ddl? ???? ????
    open-in-view: false
    show-sql: true                            #sql?? ???
    properties:
      hibernate:
        format_sql: true                      #??? ??? db???? ???? ?? ??? ???
        default_batch_fetch_size: 100         #??? ??? ???? ??? select? ???? ??? ????
  sql.init.mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
#  thymeleaf.cache: false

---

#for testdb

spring:
  config:
    activate:
      on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board:mode=mysql
#    driverClassName: org.h2.Driver
#  sql:
#    init:
#      mode: always
#  test.database.replace: none
